name: Deploy Vite app to GitHub Pages

on:
  push:
    branches:
      - main # 你主分支如果不是 main 就改成自己的
  workflow_dispatch: # 允许手动触发一次

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
